#macro PLAYER_LEG_HIDE_TIME (ONE_SECOND * 3)
#macro PLAYER_NOT_MOVING_SPEED 0.3
#macro ITEM_HALF_WIDTH 16
#macro BEAM_ACTIVE_ANGLE 8
#macro BLOCK_SIZE 40
#macro PLAYER_BEAM_UNHEAT_TIME (ONE_SECOND * 3)
#macro PLAYER_BEAM_HEAT_TIME (ONE_SECOND * 3.5)
#macro PLAYER_ITEM_RETRACT_TIME 0.3